FROM golang:1.23-alpine AS builder

RUN apk add --no-cache git

WORKDIR /app
  
  # Копируем ВЕСЬ код сразу
COPY . .
  
  # Добавляем templ в go.mod (принудительно)
RUN go get github.com/a-h/templ
  
  # Устанавливаем templ
RUN go install github.com/a-h/templ/cmd/templ@latest
  
  # Генерируем шаблоны (теперь templ есть в go.mod)
RUN templ generate
  
  # ТЕПЕРЬ делаем go mod tidy - после генерации, когда templ уже используется
RUN go mod tidy
  
  # Собираем приложение
RUN go build -o integrator ./cmd/integrator

FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /app

COPY --from=builder /app/integrator /app/
COPY --from=builder /app/config /app/config
COPY --from=builder /app/migrations /app/migrations

EXPOSE 8080

CMD ["./integrator"]